name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    env:
      NODE_VER: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js v${{env.NODE_VER}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VER}}
          cache: pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm -r install

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test run
